# slightly modified GitHub Go starter workflow
# added caching and removed build
name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15.6
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.6

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: make test
    
    - name: Validate yaml
      uses: stefanprodan/kube-tools@v1
      with:
        command: |
          kustomize build ./deploy | kubeval --strict

    # run kyverno cli and use v1 instead of v1.0.0
    - name: Validate policies
      uses: gbaeke/kyverno-action@v1
      with:
        command: |
          kyverno apply ./policies --resource=./deploy/deployment.yaml
